# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CaptureWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CaptureWindow(object):
    def setupUi(self, CaptureWindow):
        CaptureWindow.setObjectName("CaptureWindow")
        CaptureWindow.resize(831, 608)
        self.centralwidget = QtWidgets.QWidget(CaptureWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 811, 579))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(500, 500))
        self.imageLabel.setMaximumSize(QtCore.QSize(6000, 16777215))
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.usernameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLabel.sizePolicy().hasHeightForWidth())
        self.usernameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.capturePushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capturePushButton.setObjectName("capturePushButton")
        self.horizontalLayout.addWidget(self.capturePushButton)
        self.returnPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.returnPushButton.setObjectName("returnPushButton")
        self.horizontalLayout.addWidget(self.returnPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.processTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processTextEdit.sizePolicy().hasHeightForWidth())
        self.processTextEdit.setSizePolicy(sizePolicy)
        self.processTextEdit.setMinimumSize(QtCore.QSize(0, 500))
        self.processTextEdit.setReadOnly(True)
        self.processTextEdit.setObjectName("processTextEdit")
        self.verticalLayout_2.addWidget(self.processTextEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.processPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.processPushButton.setObjectName("processPushButton")
        self.verticalLayout_2.addWidget(self.processPushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        CaptureWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaptureWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 21))
        self.menubar.setObjectName("menubar")
        CaptureWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaptureWindow)
        self.statusbar.setObjectName("statusbar")
        CaptureWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CaptureWindow)
        QtCore.QMetaObject.connectSlotsByName(CaptureWindow)

    def retranslateUi(self, CaptureWindow):
        _translate = QtCore.QCoreApplication.translate
        CaptureWindow.setWindowTitle(_translate("CaptureWindow", "Capture"))
        self.imageLabel.setText(_translate("CaptureWindow", "Image"))
        self.usernameLabel.setText(_translate("CaptureWindow", "Username Label"))
        self.capturePushButton.setText(_translate("CaptureWindow", "Capture"))
        self.returnPushButton.setText(_translate("CaptureWindow", "Return"))
        self.processPushButton.setText(_translate("CaptureWindow", "Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaptureWindow = QtWidgets.QMainWindow()
    ui = Ui_CaptureWindow()
    ui.setupUi(CaptureWindow)
    CaptureWindow.show()
    sys.exit(app.exec_())

